image: elixir:latest

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

mix:
  script:
  - mix test --cover
  - mix check

cache:
  paths:
    - _build
    - deps
